{
  "lake": {
    "topography": "topography.asc",
    "water_level": -10000.0,
    "xmin": 0.0,
    "xmax": 2.0,
    "ymin": 0.0,
    "ymax": 1.0
  },
  "topo_files": {
    "topography": "topography.asc",
    "mask_raster": "mask.asc",
    "missing_value": -9999.0
  },
  "computation": {
    "boundary": "extrap",
    "cell_size": 0.1,
    "cfl_max": 0.5,
    "cfl_target": 0.25,
    "damping": 1.0,
    "dry_limit": 0.0001,
    "initial_mass": false,
    "limiter": "mc",
    "max_iter": 5000000,
    "mode": "internal_shoreline",
    "nb_grid": 20,
    "nb_simul": 10,
    "refinement": 1,
    "t_0": 0.0,
    "t_max": 1.0
  },
  "gauges": {
    "gauge_recording": false
  },
  "output": {
    "delta_t": 0.1,
    "output_directory": "_output",
    "output_format": "binary",
    "verbosity": 0
  },
  "rheology": {
    "Strickler": [
      1000000000000.0,
      1000000000000.0
    ],
    "friction": false,
    "friction_break_elevation": 0.0,
    "friction_depth_limit": 1000000000000.0,
    "gravity": 9.81,
    "rho": 1000.0,
    "wave_tolerance_flag": 1000000000000.0
  }
}
