c
c
c     =====================================================
      subroutine flux2(ixy,maxm,meqn,maux,mbc,mx,
     &                 q1d,dtdx1d,aux1,aux2,aux3,
     &                 faddm,faddp,gaddm,gaddp,cfl1d,
     &                 rpn2,rpt2)
!!     &                 fwave,s,amdq,apdq,rpn2,rpt2)
c     =====================================================
c
c     # clawpack routine ...  modified for AMRCLAW
c
c--------------------------------------------------------------------
c     # flux2fw is a modified version of flux2 to use fwave instead of wave.
c     # A modified Riemann solver rp2n must be used in conjunction with this
c     # routine, which returns fwave's instead of wave's.
c     # See http://amath.washington.edu/~claw/fwave.html
c
c     # Limiters are applied to the fwave's, and the only significant
c     # modification of this code is in the "do 119" loop, for the
c     # second order corrections.
c
c--------------------------------------------------------------------
c
c
c     # Compute the modification to fluxes f and g that are generated by
c     # all interfaces along a 1D slice of the 2D grid.
c     #    ixy = 1  if it is a slice in x
c     #          2  if it is a slice in y
c     # This value is passed into the Riemann solvers. The flux modifications
c     # go into the arrays fadd and gadd.  The notation is written assuming
c     # we are solving along a 1D slice in the x-direction.
c
c     # fadd(i,.) modifies F to the left of cell i
c     # gadd(i,.,1) modifies G below cell i
c     # gadd(i,.,2) modifies G above cell i
c
c     # The method used is specified by method(2:3):
c
c         method(2) = 1 if only first order increment waves are to be used.
c                   = 2 if second order correction terms are to be added, with
c                       a flux limiter as specified by mthlim.
c
c         method(3) = 0 if no transverse propagation is to be applied.
c                       Increment and perhaps correction waves are propagated
c                       normal to the interface.
c                   = 1 if transverse propagation of increment waves
c                       (but not correction waves, if any) is to be applied.
c                   = 2 if transverse propagation of correction waves is also
c                       to be included.
c
c     Note that if mcapa>0 then the capa array comes into the second
c     order correction terms, and is already included in dtdx1d:
c     If ixy = 1 then
c        dtdx1d(i) = dt/dx                      if mcapa= 0
c                  = dt/(dx*aux(i,jcom,mcapa))  if mcapa = 1
c     If ixy = 2 then
c        dtdx1d(j) = dt/dy                      if mcapa = 0
c                  = dt/(dy*aux(icom,j,mcapa))  if mcapa = 1
c
c     Notation:
c        The jump in q (q1d(i,:)-q1d(i-1,:))  is split by rpn2 into
c            amdq =  the left-going flux difference  A^- Delta q
c            apdq = the right-going flux difference  A^+ Delta q
c        Each of these is split by rpt2 into
c            bmasdq = the down-going transverse flux difference B^- A^* Delta q
c            bpasdq =   the up-going transverse flux difference B^+ A^* Delta q
c        where A^* represents either A^- or A^+.
c

c      #  modifications for GeoClaw

c--------------------------flux2fw_geo.f--------------------------
c     When use_fwave_positivity_limiter is enabled, first-order mass
c     terms are retained as true interface fluxes and the second-order
c     stencil is evaluated over the extra faces needed by step2.  The
c     module flag is false by default, preserving the historical path.
c---------------------last modified 1/04/05-----------------------------

      use amr_module, only: use_fwaves, mwaves, method
      use amr_module, only: mthlim
      use geoclaw_module, only: coordinate_system, earth_radius,
     &     deg2rad, relimit => use_fwave_positivity_limiter

      implicit double precision (a-h,o-z)

      external rpn2, rpt2
      dimension  q1d(meqn, 1-mbc:maxm+mbc)

      dimension  bmasdq(meqn, 1-mbc:maxm+mbc)
      dimension  bpasdq(meqn, 1-mbc:maxm+mbc)
      dimension  cqxx(meqn, 1-mbc:maxm+mbc)
      dimension  faddm(meqn,1-mbc:maxm+mbc)
      dimension  faddp(meqn,1-mbc:maxm+mbc)
      dimension  gaddm(meqn,1-mbc:maxm+mbc, 2)
      dimension  gaddp(meqn,1-mbc:maxm+mbc, 2)
      dimension  dtdx1d(1-mbc:maxm+mbc)
      dimension  aux1(maux, 1-mbc:maxm+mbc)
      dimension  aux2(maux, 1-mbc:maxm+mbc)
      dimension  aux3(maux, 1-mbc:maxm+mbc)
c
      dimension  s(mwaves, 1-mbc:maxm+mbc)
      dimension  fwave(meqn, mwaves, 1-mbc:maxm+mbc)
      dimension  amdq(meqn, 1-mbc:maxm+mbc)
      dimension  apdq(meqn, 1-mbc:maxm+mbc)
c
      logical limit
      integer ilo, ihi

      ilo = 1
      ihi = mx+1
      if (relimit) then
         ilo = 0
         ihi = mx+2
      endif
c
      limit = .false.
      do 5 mw=1,mwaves
         if (mthlim(mw) .gt. 0) limit = .true.
   5     continue
c
c     # initialize flux increments:
c     -----------------------------
c

      do 30 jside=1,2
        do 20 i = 1-mbc, mx+mbc
          do 10 m=1,meqn
               faddm(m,i) = 0.d0
               faddp(m,i) = 0.d0
               gaddm(m,i,jside) = 0.d0
               gaddp(m,i,jside) = 0.d0
   10          continue
   20       continue
   30    continue

c
c
c     # solve Riemann problem at each interface and compute Godunov updates
c     ---------------------------------------------------------------------
c
      call rpn2(ixy,maxm,meqn,mwaves,maux,mbc,mx,q1d,q1d,
     &          aux2,aux2,fwave,s,amdq,apdq)

c
c   # Set fadd for the donor-cell upwind method (Godunov)
      if (ixy.eq.1) mu=2
      if (ixy.eq.2) mu=3
      do 40 i=1-mbc+1,mx+mbc-1
         if (coordinate_system.eq.2) then
              if (ixy.eq.1) then
                   dxdc=earth_radius*deg2rad
              else  
                  dxdc=earth_radius*cos(aux2(3,i))*deg2rad
!                  if (ixy.eq.2) dxdc=earth_radius*cos(aux2(3,i))*deg2rad  !why test again
              endif
         else
            dxdc=1.d0
         endif

          do m=1,meqn
            faddp(m,i) = faddp(m,i) - apdq(m,i)
            faddm(m,i) = faddm(m,i) + amdq(m,i)
          enddo
          if (relimit) then
            faddp(1,i) = faddp(1,i) + dxdc*q1d(mu,i)
            faddm(1,i) = faddp(1,i)
          endif
   40       continue
c
c     # compute maximum wave speed for checking Courant number:
c     Keep this reduction shared with step2_cfl so the transactional probe
c     and the accepted physical update cannot drift apart.
      call cfl_from_speeds(maxm,mwaves,mbc,mx,dtdx1d,s,cfl1d)
c
      if (method(2).eq.1) go to 130
c
c     # modify F fluxes for second order q_{xx} correction terms:
c     -----------------------------------------------------------
c
c     # apply limiter to fwaves:
      if (limit) then
         if (relimit) then
            call limiter_range(maxm,meqn,mwaves,mbc,mx,fwave,s,
     &                         mthlim,-1,mx+2)
         else
            call limiter(maxm,meqn,mwaves,mbc,mx,fwave,s,mthlim)
         endif
      endif
c
      do 120 i = ilo, ihi
c
c        # For correction terms below, need average of dtdx in cell
c        # i-1 and i.  Compute these and overwrite dtdx1d:
c
         dtdx1d(i-1) = 0.5d0 * (dtdx1d(i-1) + dtdx1d(i))
c
         do 120 m=1,meqn
            cqxx(m,i) = 0.d0
            do 119 mw=1,mwaves
c
c              # second order corrections:
               cqxx(m,i) = cqxx(m,i) + dsign(1.d0,s(mw,i))
     &            * (1.d0 - dabs(s(mw,i))*dtdx1d(i-1)) * fwave(m,mw,i)
c
  119          continue
            faddm(m,i) = faddm(m,i) + 0.5d0 * cqxx(m,i)
            faddp(m,i) = faddp(m,i) + 0.5d0 * cqxx(m,i)
  120       continue
c
c
  130  continue
c
       if (method(3).eq.0) go to 999   !# no transverse propagation
c
       if (method(2).gt.1 .and. method(3).eq.2) then
c         # incorporate cqxx into amdq and apdq so that it is split also.
          do 150 i = ilo, ihi
             do 150 m=1,meqn
                amdq(m,i) = amdq(m,i) + cqxx(m,i)
                apdq(m,i) = apdq(m,i) - cqxx(m,i)
  150           continue
          endif
c
c
c      # modify G fluxes for transverse propagation
c      --------------------------------------------
c
c
c     # split the left-going flux difference into down-going and up-going:
      call rpt2(ixy,1,maxm,meqn,mwaves,maux,mbc,mx,
     &          q1d,q1d,aux1,aux2,aux3,
     &          amdq,bmasdq,bpasdq)
c
c     # modify flux below and above by B^- A^- Delta q and  B^+ A^- Delta q:
      do 160 i = ilo, ihi
         do 160 m=1,meqn
               gupdate = 0.5d0*dtdx1d(i-1) * bmasdq(m,i)
               gaddm(m,i-1,1) = gaddm(m,i-1,1) - gupdate
               gaddp(m,i-1,1) = gaddp(m,i-1,1) - gupdate
c
               gupdate = 0.5d0*dtdx1d(i-1) * bpasdq(m,i)
               gaddm(m,i-1,2) = gaddm(m,i-1,2) - gupdate
               gaddp(m,i-1,2) = gaddp(m,i-1,2) - gupdate
  160          continue
c
c     # split the right-going flux difference into down-going and up-going:
      call rpt2(ixy,2,maxm,meqn,mwaves,maux,mbc,mx,
     &          q1d,q1d,aux1,aux2,aux3,
     &          apdq,bmasdq,bpasdq)
c
c     # modify flux below and above by B^- A^+ Delta q and  B^+ A^+ Delta q:
      do 180 i = ilo, ihi
          do 180 m=1,meqn
               gupdate = 0.5d0*dtdx1d(i-1) * bmasdq(m,i)
               gaddm(m,i,1) = gaddm(m,i,1) - gupdate
               gaddp(m,i,1) = gaddp(m,i,1) - gupdate
c
               gupdate = 0.5d0*dtdx1d(i-1) * bpasdq(m,i)
               gaddm(m,i,2) = gaddm(m,i,2) - gupdate
               gaddp(m,i,2) = gaddp(m,i,2) - gupdate
  180          continue
c
  999 continue
      return
      end
c
c     =====================================================
      subroutine step2_cfl(maxm,meqn,maux,mbc,mx,my,
     &                     qold,aux,dx,dy,dt,cflgrid,rpn2)
c     =====================================================
c
c     Compute exactly the CFL number that step2 would report, without
c     constructing flux corrections or performing transverse solves.
c
c     flux2 computes cfl1d immediately from the wave speeds returned by
c     rpn2.  Limiters, transverse propagation, positivity relimiting,
c     and flux accumulation occur later and cannot change
c     the CFL.  The same sweep bounds, slices, capacity scaling, Riemann
c     call, and reduction therefore preserve the acceptance decision.
c
c     qold and aux are private b4step2-prepared copies.
c     This routine has no observation, flux-register, solution,
c     patch-clock, or global CFL side effects.  It lives with flux2fw
c     because ordinary, multilayer, and Boussinesq builds use different
c     step2 files
c     while sharing this normal-flux implementation.
c
      use geoclaw_module, only:
     &     relimit => use_fwave_positivity_limiter
      use amr_module, only: mwaves, mcapa

      implicit double precision (a-h,o-z)

      external rpn2
      dimension qold(meqn,1-mbc:mx+mbc,1-mbc:my+mbc)
      dimension aux(max(1,maux),1-mbc:mx+mbc,
     &              1-mbc:my+mbc)
      dimension q1d(meqn,1-mbc:maxm+mbc)
      dimension aux2(max(1,maux),1-mbc:maxm+mbc)
      dimension dtdx1d(1-mbc:maxm+mbc)
      dimension fwave(meqn,mwaves,1-mbc:maxm+mbc)
      dimension s(mwaves,1-mbc:maxm+mbc)
      dimension amdq(meqn,1-mbc:maxm+mbc)
      dimension apdq(meqn,1-mbc:maxm+mbc)
      integer sweep_lo,sweep_pad,icom,jcom

      cflgrid = 0.d0
      dtdx = dt/dx
      dtdy = dt/dy

      sweep_lo = 0
      sweep_pad = 1
      if (relimit) then
         sweep_lo = -1
         sweep_pad = 2
      endif

c     Match the normal x-sweeps in step2 and the reduction in flux2.
      do j = sweep_lo,my+sweep_pad
         q1d(:,1-mbc:mx+mbc) = qold(:,1-mbc:mx+mbc,j)

         if (mcapa .gt. 0) then
            dtdx1d(1-mbc:mx+mbc) =
     &          dtdx/aux(mcapa,1-mbc:mx+mbc,j)
         else
            dtdx1d = dtdx
         endif

         if (maux .gt. 0) then
            aux2(:,1-mbc:mx+mbc) = aux(:,1-mbc:mx+mbc,j)
         endif

         jcom = j
         call rpn2(1,maxm,meqn,mwaves,maux,mbc,mx,q1d,q1d,
     &             aux2,aux2,fwave,s,amdq,apdq)

         call cfl_from_speeds(maxm,mwaves,mbc,mx,
     &                        dtdx1d,s,cfl1d)
         cflgrid = dmax1(cflgrid,cfl1d)
      enddo

c     Match the normal y-sweeps in step2 and the reduction in flux2.
      do i = sweep_lo,mx+sweep_pad
         q1d(:,1-mbc:my+mbc) = qold(:,i,1-mbc:my+mbc)

         if (mcapa .gt. 0) then
            dtdx1d(1-mbc:my+mbc) =
     &          dtdy/aux(mcapa,i,1-mbc:my+mbc)
         else
            dtdx1d = dtdy
         endif

         if (maux .gt. 0) then
            aux2(:,1-mbc:my+mbc) = aux(:,i,1-mbc:my+mbc)
         endif

         icom = i
         call rpn2(2,maxm,meqn,mwaves,maux,mbc,my,q1d,q1d,
     &             aux2,aux2,fwave,s,amdq,apdq)

         call cfl_from_speeds(maxm,mwaves,mbc,my,
     &                        dtdx1d,s,cfl1d)
         cflgrid = dmax1(cflgrid,cfl1d)
      enddo

      return
      end
c
c     =====================================================
      subroutine cfl_from_speeds(maxm,mwaves,mbc,mx,
     &                           dtdx1d,s,cfl1d)
c     =====================================================
c
c     Reduce normal Riemann wave speeds with Clawpack's signed,
c     capacity-aware CFL definition.  Both flux2 and the transactional
c     CFL-only probe call this routine, so the acceptance criteria share
c     one implementation rather than two formulas that can drift.
c
c     Keep this helper here: the multilayer build supplies its own
c     step2 but uses this same flux file.
c
      implicit double precision (a-h,o-z)

      dimension dtdx1d(1-mbc:maxm+mbc)
      dimension s(mwaves,1-mbc:maxm+mbc)

      cfl1d = 0.d0
      do mw=1,mwaves
         do i=1,mx+1
c           # A right-going wave uses the capacity of the cell on its
c           # right; a left-going wave uses the cell on its left.
            cfl1d = dmax1(cfl1d,dtdx1d(i)*s(mw,i),
     &                          -dtdx1d(i-1)*s(mw,i))
         enddo
      enddo

      return
      end
